version: '2'
services:
  odoo_postgresql:
    container_name: odoo_postgresql
    image: docker.io/bitnami/postgresql:13
    volumes:
      - ./postgresql_data:/bitnami/postgresql
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_odoo
      - POSTGRESQL_DATABASE=bitnami_odoo
  odoo:
    container_name: odoo
    image: docker.io/bitnami/odoo:15
    ports:
      - '8069:8069'
    volumes:
      - ./odoo_data:/bitnami/odoo
    depends_on:
      - odoo_postgresql
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - ODOO_DATABASE_HOST=odoo_postgresql
      - ODOO_DATABASE_PORT_NUMBER=5432
      - ODOO_DATABASE_USER=bn_odoo
      - ODOO_DATABASE_NAME=bitnami_odoo
      # User & PW
      - ODOO_EMAIL=user@example.com
      - ODOO_PASSWORD=bitnami